[profile.default]
src = "src"
out = "out"
libs = ["lib"]


fs_permissions = [{access = "read-write", path = "./"}, { access = "read", path = "./broadcast" },
    { access = "read", path = "./reports" }]

remapping = [
    '@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/',
    'murky/=lib/murky/'
    ]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
